version: '3.8' # กำหนด docker version
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ltsproject
      MYSQL_USER: ltsproject
      MYSQL_PASSWORD: simplePassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_ltsproject:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ltsproject
      PMA_PASSWORD: simplePassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data_ltsproject: # กำหนดชื่อ volume ที่ต้องการจะสร้าง
    driver: local