version: '3.8' # กำหนด docker version
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrm-dev
    restart: always
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: ltsproject
      POSTGRES_USER: ltsproject
      POSTGRES_PASSWORD: simplePassword
      POSTGRES_MULTIPLE_DATABASES: ltsproject
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "ltsproject"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_ltsproject:/var/lib/postgresql/data

volumes:
  postgres_data_ltsproject: # กำหนดชื่อ volume ที่ต้องการจะสร้าง
    driver: local